### ISSUE TITLE
The lab does not work

### ISSUE THREAD

**Issue by ppecomte** [watson-developer-cloud/image-analysis#1]
Hello , I am testing the lab for a hackaton that occurs tomorrow July 9th: The cut out version of the application works and analyses images
However the translation part does not work : i  see it refers to the old machine translation service and not the curent language translation: Can you do something about the issue ?

**Comment by germanattanasio** [comment]
We need to update the machine translation service probably. I will take a look at this.

**Comment by germanattanasio** [comment]
@aldelucca1 can you update this to use the language-translation service instead of machine-translation ?

There is a hackathon Today and they need it

**Comment by germanattanasio** [comment]
I just updated text-to-speech so we just need to update machine-translation

**Comment by germanattanasio** [comment]
FIxed by @aldelucca1
