### ISSUE TITLE
What is needed to support the new Visual Recognition V3 ?

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/image-analysis#10]
Hello , 
What is needed to have this application support the new WVisual Recognition V3 service ? 
The service comes with an API key and no user/pwd.

**Comment by nfriedly** [comment]
Aside from the credentials change, the new V3 of the service has a significant change to allow each classifier instance to support multiple classes. (Before to classify fruit as bananas/apples/grapes, you'd have to create three classifier instances, one for each fruit - with v3 you can create a single instance that recognizes all three.)

This necessitated some changes to many of the APIs, so while it's not an unbearable amount of work to update, it will take some effort. The documentation has additional information: http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/visual-recognition/upgrading-migrating.shtml#upgrading

**Comment by PhilippeComte** [comment]
Many thanks . I had overlooked those modifications within the API
