### ISSUE TITLE
can not run this in live-edit mode

### ISSUE THREAD

**Issue by peterschleinitz** [watson-developer-cloud/image-analysis#12]
Error log: 
> node app.js
listening at: 61422
error: { code: 404, error: 'Not Found' } url: /bluemix-debug/manage/tools/runtime
image-analysis-jps-2040.mybluemix.net - [28/07/2016:19:55:01.504 +0000] "GET /bluemix-debug/manage/tools/runtime HTTP/1.1" 404 0 32 "-" "Jakarta Commons-HttpClient/3.1" 108.168.250.154:19771 x_forwarded_for:"198.11.229.213" x_forwarded_proto:"https" vcap_request_id:1b9733a7-2683-4240-4e91-531aa0b25032 response_time:0.036632526 app_id:52b3f8b2-9bef-4d70-b955-b71893505612 x_global_transaction_id:"2595004031"

seems to be related to http://stackoverflow.com/questions/37448998/classifying-images-using-bluemix

why isn't there a app.get('/', function(req, res) line?

**Comment by germanattanasio** [comment]
Because we use a simple `index.html` file. By default your browser will look into that file.
