### ISSUE TITLE
Ok on MacOs ... but not on Windows

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/image-analysis#14]
Hello , I have been able to run the app on MacOS... but not on Windows  7 yet (app on local not on Bluemix)
On Windows , the app is connected to the Visual Recognition ... but the Text to Speech does not work.
There is a message saying that /translate is not found ...
Any idea ?
Many thanks

Seems that there is a mkdir command that may be ok for running on Bluemix or Linux style OS but not windows

**Comment by germanattanasio** [comment]
Hi @PhilippeComte I was able to run the app in Windows. Can you double check? I'm closing this for now.
