### ISSUE TITLE
Image Analysis instructions need a bit of an update.  I'm a newbie.

### ISSUE THREAD

**Issue by cmartinwilson** [watson-developer-cloud/image-analysis#8]
Ginnie R (CEO) has asked us all to get involved with Cognitive APIs.  So I'm following the instructions to do what was asked.  Try out examples in bluemix. 

1st thanks for the instructions, without them, I would not have gotten as far as I have.

The instructions , assume a couple of things or have tiny errors in them, that newbie can get tripped up on.

 https://github.com/watson-developer-cloud/image-analysis/blob/master/INSTRUCTIONS.md 

I was able to try out the image analysis without the code changes, not without mishap, but I did get it done.

Now I want to do the steps for the code changes.  This is where I got tripped up.

 1. The Deploy step does not automatically create the 2 api services Visual Reg and Text to speech.  [I had to add them, before adding them I could not understand why I wasn't getting the speaker icon at the bottom of the page, and also the watson analysis spiral was not appearing]

 2. Modifying the Code, you reference Jazz repo, but for a newbie, there is no Jazz rep in the dashboard, there is no Git link, there is only a new GIT (I believe text), you have to click git to get it to configure, something and then the GIT url in your dashboard will appear, so you can click it to edit your code.

 3.Within the Git repo, the instructions do not say to create the lt.js file in a routes folder, it only later that you recognize that the file should be in the routes folder.

 3. the app.js file was not created in my git folder. Not sure why.  later I found another image analysis folder that had the app.js file.  I copied that file into my other image analysis folder. Don't know why I have 2 image analysis git folders.  And then was able to uncomment line 31.

 4. I was getting an error in my lt.js file that I copied from the instructions.  There is some hint that I need to add this line to the file /*eslint-env node */.  I did that and the error went away.  But I'm not sure that was correct.

 5. Commit my 2 file changes.  There is an error in the screen shot, it shows a mt.js file in routes folder, and not the lt.js file.

 6.Build and Deply step. I don't know how to create a pipeline. The instructions did not give the instructions on how to create a pipe line.  I used the pipeline editor, but to no avail. I can't get my code to build and deploy.  I'm almost at the finish line.  But I am stuck.  There is a little video on staging that while pretty, doesn't tell me how to create the pipeline.

Also there is this line that appears in the header of the git view  <html> <head><title>404 Not Found</title></head> <body bgcolor="white"> <center><h1>404 Not Found</h1></center> <hr><center>nginx/1.8.0</center> </body> </html>  I don't know where its coming from or how to get rid of it.

Would appreciate some updates to the image analysis instructions.

**Comment by germanattanasio** [comment]
Hey @Repjarms can you take a look at this? I think the labs need to be updated because jazzhub was updated recently.

**Comment by jzhang300** [comment]
@cmartinwilson I'm looking through this right now step by step and I'm having a hard time reproducing your problems.  Were you able to figure out your issues?

**Comment by cmartinwilson** [comment]
You can't reproduce the problems because you're not starting from a fresh 
environment.  Your environment is already tainted.
What I notice is that if you've gone thru trying to do the steps you will 
never ever see what a fresh new person sees the 1st time.

Also, the screen shots do not match what a newbie sees the 1st time.

I would like to have an emeeting with you to show you were the errors are 
if you don't mind.

Regards,

Connie Martin-Wilson, PMP®
SBS/Cloud Platform Release Program Mgr
978-899-2837, T/L 276-2837, cmartin_wilson@us.ibm.com

**Comment by jzhang300** [comment]
I agree!  Let's meet some time tomorrow to see what's going on.  My email is jzhang300@us.ibm.com
