### ISSUE TITLE
Exceed memory limit.

### ISSUE THREAD

**Issue by cmartinwilson** [watson-developer-cloud/image-analysis#9]
Every time I tried to deploy, I keep getting this error message.

"Server error, status code: 400, error code: 100005, message: You have exceeded your organization's memory limit.
Finished: FAILED"

I only have a trial version of Bluemix.  What can I do to get more memory?

**Comment by nfriedly** [comment]
Hi @cmartinwilson,

Unfortunately, you have to pay bluemix for more memory.  However, you can try lowering the `memory` line in your (manifest.yml)[https://github.com/watson-developer-cloud/image-analysis/blob/master/manifest.yml#L16] to whatever you have left, or shut down / delete other apps on your account to free up memory.
